// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.CardView = (function(_super) {
    __extends(CardView, _super);

    function CardView() {
      _ref = CardView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    CardView.prototype.className = 'card';

    CardView.prototype.initialize = function() {
      var _this = this;
      this.model.on('change', function() {
        return _this.render;
      });
      return this.render();
    };

    CardView.prototype.render = function() {
      var cardId, output, template;
      cardId = "card-" + this.model.translateValue();
      template = document.getElementById(cardId).innerHTML;
      output = Mustache.render(template, {
        suit: {
          symbol: this.model.translate(this.model.get('suitName')),
          name: this.model.get('suitName').toLowerCase()
        }
      });
      this.$el.children().detach().end().html;
      this.$el.html(output);
      this.$el.addClass(this.model.get("suitName").toLowerCase());
      if (!this.model.get('revealed')) {
        return this.$el.addClass('covered');
      }
    };

    return CardView;

  })(Backbone.View);

}).call(this);

/*
//@ sourceMappingURL=CardView.map
*/
