// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.CardView = (function(_super) {
    __extends(CardView, _super);

    function CardView() {
      return CardView.__super__.constructor.apply(this, arguments);
    }

    CardView.prototype.className = 'card';

    CardView.prototype.initialize = function() {
      this.model.on('change', (function(_this) {
        return function() {
          return _this.render;
        };
      })(this));
      return this.render();
    };

    CardView.prototype.render = function() {
      var cardId, output, template;
      if (this.model.get("revealed")) {
        cardId = "card-" + this.model.translateValue();
      } else {
        cardId = "card-back";
      }
      template = document.getElementById(cardId).innerHTML;
      output = Mustache.render(template, {
        suit: {
          symbol: this.model.translate(this.model.get('suitName')),
          name: this.model.get('suitName').toLowerCase()
        }
      });
      this.$el.children().detach().end().html;
      this.$el.html(output);
      return this.$el.addClass(this.model.get("suitName").toLowerCase());
    };

    return CardView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=CardView.map
