// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.HistoryView = (function(_super) {
    __extends(HistoryView, _super);

    function HistoryView() {
      _ref = HistoryView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    HistoryView.prototype.className = "history";

    HistoryView.prototype.tagName = "table";

    HistoryView.prototype.initialize = function() {
      var _this = this;
      this.collection.on("add remove change", function() {
        return _this.render();
      });
      return this.render();
    };

    HistoryView.prototype.render = function() {
      this.$el.children().detach();
      this.$el.append($("<thead><th class='titleRow' colSpan='3' style='text-align:center'>Plays</th></thead>"));
      this.$el.append($("<tr>").append($("<th class='headerRow'>").text("Player")).append($("<th class='headerRow'>").text("Dealer")).append($("<th class='headerRow'>").text("Chip Count")));
      this.$el.append(this.collection.map(function(play) {
        return new HistoryEntryView({
          model: play
        }).$el;
      }));
      return this.$el.append($("<tfoot><td></td></tfoot>"));
    };

    return HistoryView;

  })(Backbone.View);

}).call(this);

/*
//@ sourceMappingURL=HistoryView.map
*/
