// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.HistoryEntryView = (function(_super) {
    __extends(HistoryEntryView, _super);

    function HistoryEntryView() {
      _ref = HistoryEntryView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    HistoryEntryView.prototype.className = "play";

    HistoryEntryView.prototype.tagName = "tr";

    HistoryEntryView.prototype.initialize = function() {
      return this.render();
    };

    HistoryEntryView.prototype.render = function() {
      var hand, td1, td2, td3;
      hand = this.model.get("playerHand");
      td1 = $("<td class = 'dataRow'></td>");
      hand.each(function(card) {
        return td1.html(td1.html() + card.get("suitName") + " - " + card.get("rankName") + "<br/>");
      });
      hand = this.model.get("dealerHand");
      td2 = $("<td class = 'dataRow'></td>");
      hand.each(function(card) {
        return td2.html(td2.html() + card.get("suitName") + " - " + card.get("rankName") + "<br/>");
      });
      td3 = $("<td class = 'dataRow'></td>").text(this.model.get("chipCount"));
      return this.$el.append(td1).append(td2).append(td3);
    };

    return HistoryEntryView;

  })(Backbone.View);

}).call(this);

/*
//@ sourceMappingURL=HistoryEntryView.map
*/
