// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.HistoryView = (function(_super) {
    __extends(HistoryView, _super);

    function HistoryView() {
      return HistoryView.__super__.constructor.apply(this, arguments);
    }

    HistoryView.prototype.className = "history";

    HistoryView.prototype.tagName = "table";

    HistoryView.prototype.initialize = function() {
      this.collection.on("add remove change", (function(_this) {
        return function() {
          return _this.render();
        };
      })(this));
      return this.render();
    };

    HistoryView.prototype.render = function() {
      this.$el.children().detach();
      this.$el.append($("<thead><th class='titleRow' colSpan='3' style='text-align:center'>Plays</th></thead>"));
      this.$el.append($("<tr>").append($("<th class='headerRow'>").text("Player")).append($("<th class='headerRow'>").text("Dealer")).append($("<th class='headerRow'>").text("Chip Count")));
      this.$el.append(this.collection.map(function(play) {
        return new HistoryEntryView({
          model: play
        }).$el;
      }));
      return this.$el.append($("<tfoot><td></td></tfoot>"));
    };

    return HistoryView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=HistoryView.map
