// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.HistoryEntryView = (function(_super) {
    __extends(HistoryEntryView, _super);

    function HistoryEntryView() {
      return HistoryEntryView.__super__.constructor.apply(this, arguments);
    }

    HistoryEntryView.prototype.className = "play";

    HistoryEntryView.prototype.tagName = "tr";

    HistoryEntryView.prototype.initialize = function() {
      return this.render();
    };

    HistoryEntryView.prototype.render = function() {
      var hand, td1, td2, td3;
      td1 = $("<td class = 'dataRow'></td>");
      hand = this.model.get("playerHand");
      hand.each((function(_this) {
        return function(card) {
          return td1.append(new CardView({
            model: card
          }).$el.addClass("smallCard"));
        };
      })(this));
      td2 = $("<td class = 'dataRow'></td>");
      hand = this.model.get("dealerHand");
      hand.each((function(_this) {
        return function(card) {
          return td2.append(new CardView({
            model: card
          }).$el.addClass("smallCard"));
        };
      })(this));
      td3 = $("<td class = 'dataRow'></td>").text(this.model.get("chipCount"));
      return this.$el.append(td1).append(td2).append(td3);
    };

    return HistoryEntryView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=HistoryEntryView.map
