// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.App = (function(_super) {
    __extends(App, _super);

    function App() {
      this.dealerPlayCard = __bind(this.dealerPlayCard, this);
      _ref = App.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    App.prototype.initialize = function() {
      var deck;
      this.set('deck', deck = new Deck());
      return this.dealNewHand();
    };

    App.prototype.dealerPlay = function() {
      this.get("dealerHand").at(0).set("revealed", true);
      return setTimeout(this.dealerPlayCard, 1000);
    };

    App.prototype.dealerPlayCard = function() {
      if (this.get("dealerHand").scores()[0] < 17) {
        this.get("dealerHand").hit();
      }
      if (this.get("dealerHand").scores()[0] < 17) {
        return setTimeout(this.dealerPlayCard, 1000);
      } else if (this.get("dealerHand").scores()[0] > 21) {
        console.log("Dealer lose!!!");
        return this.restartGame();
      } else {
        if (this.get("dealerHand").scores()[0] > this.get("playerHand").scores()[0]) {
          console.log("dealer wins!");
        } else if (this.get("dealerHand").scores()[0] < this.get("playerHand").scores()[0]) {
          console.log("player wins :(");
        } else {
          console.log("game draw");
        }
        return this.restartGame();
      }
    };

    App.prototype.dealNewHand = function() {
      var _this = this;
      this.set('playerHand', this.get("deck").dealPlayer());
      this.set('dealerHand', this.get("deck").dealDealer());
      return this.get('playerHand').on('add remove change', function() {
        if (_this.get("playerHand").scores()[0] > 21) {
          console.log("Player lose!!!");
          return _this.restartGame();
        }
      });
    };

    App.prototype.restartGame = function() {
      var _this = this;
      console.log("restarting game");
      this.set('playerHand', this.get("deck").dealPlayer());
      this.set('dealerHand', this.get("deck").dealDealer());
      return this.get('playerHand').on('add remove change', function() {
        if (_this.get("playerHand").scores()[0] > 21) {
          console.log("Player lose!!!");
          return _this.restartGame();
        }
      });
    };

    return App;

  })(Backbone.Model);

}).call(this);

/*
//@ sourceMappingURL=App.map
*/
