// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Play = (function(_super) {
    __extends(Play, _super);

    function Play() {
      return Play.__super__.constructor.apply(this, arguments);
    }

    Play.prototype.initialize = function(params) {
      return this.set({
        playerHand: params.playerHand,
        dealerHand: params.dealerHand,
        chipCount: params.chipCount
      });
    };

    return Play;

  })(Backbone.Model);

}).call(this);

//# sourceMappingURL=Play.map
